import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '入门',
      key: 'sidebar-getting-started',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/getting-started',
        title: '入门',
        description: '安装、快速上手与支持的平台版本。',
      },
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: '使用指南',
      key: 'sidebar-guides',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/guides',
        title: '使用指南',
        description: '循序渐进：安装 → 互调 → TypeScript → 构建 → 日常用法。',
      },
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: '核心概念',
      key: 'sidebar-concepts',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/concepts',
        title: '核心概念',
        description: '设计模型、术语与选型摘要。',
      },
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: '选型对比',
      key: 'sidebar-compare',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/compare',
        title: '选型对比',
        description: '与 Puerts / 自管 QuickJS 等方案的定性对比（非行为契约）。',
      },
      items: [{type: 'autogenerated', dirName: 'compare'}],
    },
    {
      type: 'category',
      label: 'API 参考',
      key: 'sidebar-reference',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/reference',
        title: 'API 参考',
        description: 'TsAppDomain、特性与 zts / csharp: 速查。',
      },
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: '规范文档',
      key: 'sidebar-spec',
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/category/spec',
        title: '规范文档',
        description: '权威语义规范（上游 ZTSTest Docs/spec，经 sync 进入本站）。',
      },
      items: [{type: 'autogenerated', dirName: 'spec'}],
    },
    {
      type: 'category',
      label: '社区',
      key: 'sidebar-community',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/community',
        title: '社区',
        description: 'FAQ、测试、迁移与联系方式。',
      },
      items: [{type: 'autogenerated', dirName: 'community'}],
    },
  ],

  architectureSidebar: [
    {
      type: 'category',
      label: '架构与实现',
      key: 'sidebar-impl',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/category/impl',
        title: '架构与实现',
        description: 'Mono / Il2Cpp 实现对照（不覆盖 spec）。',
      },
      items: [{type: 'autogenerated', dirName: 'impl'}],
    },
  ],
};

export default sidebars;
